name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  asan:
    strategy:
      matrix:
        version: [14, 16, 18, 20, 22]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - run: npm install
      - run: npm run test:js-asan

  valgrind:
    strategy:
      matrix:
        version: [14, 16, 18, 20, 22]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - run: sudo apt-get update && sudo apt-get install valgrind
      - run: npm install
      - run: npm run test:js-valgrind

  build:
    uses: Datadog/action-prebuildify/.github/workflows/build.yml@main
    with:
      target-name: 'dd_pprof' # target name in binding.gyp
      package-manager: 'npm' # npm or yarn
      cache: true # enable caching of dependencies based on lockfile
      min-node-version: 14
      skip: 'linux-arm linux-ia32' # skip building for these platforms

  dev_publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: npm
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v4
        with:
          name: prebuilds
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - id: pkg
        run: |
          content=`cat ./package.json | tr '\n' ' '`
          echo "::set-output name=json::$content"
      - run: npm version --no-git-tag-version ${{ fromJson(steps.pkg.outputs.json).version }}-$(git rev-parse --short HEAD)+${{ github.run_id }}.${{ github.run_attempt }}
      - run: npm publish --tag dev

  build-successful:
    if: always()
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Determine if everything is passing
      run: exit 1
      if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
